package com.cic.base.model;

public class SpringJpaTestTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_jpa_test_table.id
     *
     * @mbg.generated Thu Oct 19 11:31:36 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_jpa_test_table.message
     *
     * @mbg.generated Thu Oct 19 11:31:36 CST 2017
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_jpa_test_table.id
     *
     * @return the value of spring_jpa_test_table.id
     *
     * @mbg.generated Thu Oct 19 11:31:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_jpa_test_table.id
     *
     * @param id the value for spring_jpa_test_table.id
     *
     * @mbg.generated Thu Oct 19 11:31:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_jpa_test_table.message
     *
     * @return the value of spring_jpa_test_table.message
     *
     * @mbg.generated Thu Oct 19 11:31:36 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_jpa_test_table.message
     *
     * @param message the value for spring_jpa_test_table.message
     *
     * @mbg.generated Thu Oct 19 11:31:36 CST 2017
     */
    public void setMessage(String message) {
        this.message = message;
    }
}